bypass. scaffolded files and templates
NethServer/nethserver-suricata pull request #16
Opened 2019-08-01 07:24 UTC by edospadoni

https://github.com/NethServer/dev/issues/5797

2019-08-01 09:09 UTC, filippocarletti requested changes

2019-08-01 09:09 UTC, filippocarletti commented on createlinks
> +    '/etc/shorewall/rules'
No need to expand /etc/shorewall/rules

2019-08-05 09:03 UTC, filippocarletti approved these changes

2019-08-05 12:47 UTC, gsanchietti approved these changes

2019-08-05 12:49 UTC, merged